# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: push_weather

on:
  workflow_dispatch:
  schedule:
    - cron: '1 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: push_weather
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Caozefu/WeatherNotification.git ~/WeatherNotification
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/WeatherNotification
          npm install
      - name: '运行 【天气推送】'
        run: |
          cd ~/WeatherNotification/src
          node app.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          CITY_CODE: ${{ secrets.CITY_CODE }}